### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AkhilaG28** [Konark-2ez/filthy-cemetery-1257#33]
**Project Feedback** :

- On the dashboard page, there is no provision for editing the expenses, it can be added or deleted only. It would have been better if an edit functionality was introduced.
- Also, the type of expenses can be in the form of a select dropdown with some options and an Other field on clicking which the text box to write other expenses can be shown which would have been a good User Experience.
- The addition of crypto is good. 
- The responsiveness of the application is quite good.
- The documentation is well written but it would have been better if the collaborators' information is given at the bottom and the link to the project at the start of the documentation.
- When a user clicks on the dashboard without logging in, it shows an alert box but it would have been better if the user gets redirected to the login page.

**Comment by Konark-2ez** [comment]
Resolved the issues
